### PR TITLE
GHA v2

### PR DESCRIPTION
**Pull request by schloerke**
Related #115 

> Carson: 
> We should remove the GHA branches and extra logic as snapshots have been ported from `vdiffr` to `testthat`

* If `tinytex` is found in the DESCRIPTION file, it is fully installed for any job: https://github.com/rstudio/shiny-workflows/blob/56e4b0e0e08b7bcf06861588b3515ebd26c240cf/setup-r-package/action.yaml#L78-L79

### CODE REVIEW

**Comment by cpsievert** [comment]
I think `{shiny-workflows}` might need `brew install pkg-config` on Mac?

https://github.com/rstudio/thematic/runs/4217003066?check_suite_focus=true#step:3:1022
https://github.com/r-spatial/sf#macos

**Comment by schloerke** [comment]
🙌 Thank you!

**Comment by schloerke** [comment]
Added fix: https://github.com/rstudio/shiny-workflows/commit/49413ac003f869f079f424ce1045b9f0a6e16884
** Re-running jobs

**Comment by schloerke** [comment]
@cpsievert macOS now passes 🥳 . Related: [`56e4b0e0e08b7bcf06861588b3515ebd26c240cf...ae73d26d34c02d763be9172eb85ee372a8e5c8a3`#diff-7d5f60492f](https://github.com/rstudio/shiny-workflows/compare/56e4b0e0e08b7bcf06861588b3515ebd26c240cf...ae73d26d34c02d763be9172eb85ee372a8e5c8a3#diff-7d5f60492fb19fae6a599d3e83ac8e7fc292939e3487b42152e8f5a3450d232dR33-R39)

**Comment by schloerke** [comment]
Merging as Windows tests are failing due to `s2` which has been fixed on GitHub

**Pull request merged**
